config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :tasks do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
  validates :expiration_deadline, presence: true
  validates :status, presence: true

  belongs_to :user

  enum status: {
    not_started_yet: 0,
    under_start: 1,
    completion: 2
  }

  scope :recent, -> { order(created_at: 'DESC') }
  scope :near_deadline, -> { order(expiration_deadline: 'ASC') }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :tasks, dependent: :destroy

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash[:alert] = 'メールアドレスかパスワードが間違っています'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
# encoding: utf-8
class TasksController < ApplicationController
  before_action :set_q, only: %i(index search)
  before_action :set_user, only: %i(create)

  def index
    @tasks = case params[:sort]
             when "作成順"
               Task.all.recent.page(1)
             when "終了期限の近い順"
               Task.all.near_deadline.page(1)
             else
               Task.all.recent.page(1)
             end
  end

  def new
    @task = Task.new
  end

  def create
    @task = @user.tasks.new(task_params)
    if @task.save
      flash[:notice] = "タスクを作成しました"
      redirect_to @task
    else
      flash.now[:alert] = "タスクの作成に失敗しました"
      render "tasks/new"
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    return unless @task.update(task_params)

    redirect_to @task, notice: "タスクを更新しました"
  end

  def edit
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      flash[:notice] = "タスクを削除しました"
      redirect_to root_path
    else
      flash.now[:alert] = "タスクの削除に失敗しました"
      redirect_to @task
    end
  end

  def search
    @tasks = @q.result(distinct: true).page(1)
  end

  private

  def task_params
    params.require(:task).permit(:name, :content, :expiration_deadline, :sort, :status)
  end

  def set_q
    @statuses = Task.statuses_i18n
    @q = Task.ransack(params[:q])
  end

  def set_user
    @user = User.create(name: "test")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TaskManagementSystem</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="navbar vavbar-light navbar-expand-sm bg-light mr-auto">
    <%= link_to "タスク管理アプリ", root_path, id: "logo", class: "navbar-brand" %>
    <nav>
      <ul class="list-unstyled navbar-nav">
        <li class="navbar-item"><%= link_to "タスク作成", new_task_path, class:"nav-link" %></li>
        <% if current_user %>
        <li class="navbar-item"><%= link_to "ログアウト", logout_path, method: :delete, class:"nav-link" %></li>
        <% else %>
        <li class="navbar-item"><%= link_to "ログイン", login_path, class:"nav-link" %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <div class="container w-75">
    <%= yield %>
  </div>
</body>

</html>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<% if @task.errors.any? %>
<% @task.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
<% end %>

<%= flash.now[:alert] %>
<%= form_with(model: @task) do |f| %>
<%= f.label :name, "タスク名" %>
<%= f.text_field :name %>

<%= f.label :content, "内容" %>
<%= f.text_area :content, size: "30*5" %>

<%= f.label :status, "ステータス" %>
<%= f.select :status, Task.statuses_i18n.invert  %>

<%= f.label :expiration_deadline, "終了期限" %>
<%= f.datetime_local_field :expiration_deadline %>

<%= f.submit "更新" %>
<% end %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<%= flash[:notice] %>
<%= form_with model: @task, url: tasks_path, method: :get do |f| %>
<%= f.select :sort, [['作成順', "作成順"], ['終了期限の近い順', "終了期限の近い順"]], { selected: '作成順' } , { class: "form-select" } %>
<%= f.submit "ソート", class: "btn btn-primary" %>
<% end %>

<%= search_form_for @q, url: search_tasks_path do |f| %>

<%= f.label :name_cont, class: "form-label" %>
<%= f.search_field :name_cont, class: "form-control" %>

<%= f.label :status_eq_any, "未着手", class: "form-label" %>
<%= f.check_box :status_eq_any, { multiple: true, include_hidden: false, class: "form-check-input" }, 0 %>
<%= f.label :status_eq_any, "着手中" %>
<%= f.check_box :status_eq_any, { multiple: true, include_hidden: false, class: "form-check-input" }, 1 %>
<%= f.label :status_eq_any, "完了" %>
<%= f.check_box :status_eq_any, { multiple: true, include_hidden: false, class: "form-check-input" }, 2 %>

<%
=begin 
%>
<% @statuses.each do |status| %>
<%= debug status %>
<%= f.label :status_eq_any, status[1] %>
<%= f.check_box :status_eq_any, { multiple: true, include_hidden: false }, status[0] %>


<% end %>
<%
=end 
%>

<%= f.submit "検索", class:"btn btn-primary" %>
<% end %>

<ul class="tasks list-unstyled mt-4 m-auto">
  <% @tasks.each do |task| %>
  <li class="list-task card">
    <div class="task-name card-header">
      <%= link_to task.name, task_path(task.id) %>
    </div>
    <div class="card-body">
      <h5>内容</h5>
      <div class="task-content">
        <%= task.content %>
      </div>
      <h5>ステータス</h5>
      <div class="task-status">
        <%= task.status_i18n %>
      </div>
      <h5>終了期限</h5>
      <div class="task-expiration-deadline">
        <%= task.expiration_deadline.to_s(:datetime) %>
      </div>
    </div>
  </li>
  <% end %>

</ul>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>タスク新規作成</h1>

<% if @task.errors.any? %>
<% @task.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
<% end %>

<%= flash.now[:alert] %>
<%= form_with(model: @task) do |f| %>
<%= f.label :name, "タスク名", class: "form-label" %>
<%= f.text_field :name, class: "form-control" %>

<%= f.label :content, "内容", class: "form-label" %>
<%= f.text_area :content, size: "30*5", class: "form-control" %>

<%= f.label :expiration_deadline, "終了期限", class: "form-label" %>
<%= f.datetime_local_field :expiration_deadline, class: "form-control" %>

<%= f.submit "登録", class: "btn btn-primary" %>
<% end %>

app/views/tasks/search.html.erb
<h1>検索結果</h1>

<%= flash[:notice] %>
<%= form_with model: @task, url: tasks_path, method: :get do |f| %>
<%= f.select :sort, [['作成順', "作成順"], ['終了期限の近い順', "終了期限の近い順"]], selected: '作成順' %>
<%= f.submit "ソート" %>
<% end %>

<%= search_form_for @q, url: search_tasks_path do |f| %>

<%= f.label :name_cont %>
<%= f.search_field :name_cont %>

<% @statuses.each do |status| %>
<%= f.check_box :status_eq_any, { multiple: true, include_hidden: false }, status[0] %>
<%= f.label status[1] %>
<% end %>

<%= f.submit %>
<% end %>

<ul class="tasks">
  <% @tasks.each do |task| %>
  <li class="list-task">
    <h2>タスク名</h2>
    <div class="task-name">
      <%= task.name %>
    </div>
    <h2>内容</h2>
    <div class="task-content">
      <%= task.content %>
    </div>
    <h2>終了期限</h2>
    <div class="task-expiration-deadline">
      <%= task.expiration_deadline.to_s(:datetime) %>
    </div>
  </li>
  <% end %>
</ul>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>

<%= flash[:notice] %>
<h2>タスク名</h2>
<%= @task.name %>
<h2>内容</h2>
<%= @task.content %>
<h2>ステータス</h2>
<%= @task.status_i18n %>
<h2>終了期限</h2>
<%= @task.expiration_deadline.to_s(:datetime) %>

<%= link_to "更新ページへ", edit_task_path(@task) %>
<%= link_to "削除", @task, method: :delete %>

app/views/users/show.html.erb
<h1>ユーザー</h1>